### ISSUE TITLE
add command-line option to position window

### ISSUE THREAD

**Issue by elenzil** [jshrake/grimoire#42]
eg "gravity" or something simpler like Position.

this would help me a lot when quitting and restarting Grimoire frequently.

**Comment by jshrake** [comment]
Thanks for filing this issue, I've been meaning to open something similar. I would like 2 ways to specify the window position + size from the command line:

- [ ] Gravity: `--gravity [left,right,top,bottom,full]`. These would all make the window half the screen size anchored to the appropriate edge, except for the last one which would make the window full screen.
- [ ] Exact: `--x`, `--y`, `--w`, `--h`. Specify the top-left corner of the window in pixel space (x,y) and the pixel width and height (`--w`, `--h`). We already have `--width` and `--height` right now, but it would be nice to abbreviate them

**Comment by elenzil** [comment]
what about letting `-w` and `-h` accept `%` after the number to indicate screen percentage instead of pixels, and then having --gravity behave similar to [imagemagick](http://www.imagemagick.org/script/command-line-options.php#gravity) ?
in my case, i've been running Grimoire as a very small window in the lower-right, which would be nice as `-w 200 -h 150 --gravity lower-right` or something

**Comment by jshrake** [comment]
> what about letting -w and -h accept % after the number to indicate screen percentage instead of pixels, and then having --gravity behave similar to imagemagick ?

This makes complete sense and I like it better than my previous suggestion! If you end up working on this before I do, please just assign yourself to the issue and I'd be happy to help land a PR. I'll assign the issue to myself if I start working on it.
