### ISSUE TITLE
Consider renaming the "audio" resource to "sound"

### ISSUE THREAD

**Issue by jshrake** [jshrake/grimoire#47]
I type sound every time and it never works. I think it's a sign.

**Comment by Atul9** [comment]
Hi @jshrake I have opened up a PR - https://github.com/jshrake/grimoire/pull/52, please check

**Comment by jshrake** [comment]
Hi! Thank you for the contribution. This issue was more of a note to myself to investigate rather than a call to action. However, after inspecting #52, I find that I don't actually like how "sound" sounds. Additionally, #52 breaks functionality due to the gstreamer pipeline changes. This exchange https://english.stackexchange.com/questions/8420/differences-between-audio-and-sound also leads me to believe that audio is indeed the correct name to use.
