### ISSUE TITLE
--fps option has no effect

### ISSUE THREAD

**Issue by elenzil** [jshrake/grimoire#58]
not sure where the bug got introduced,
but in version  0.2.1, hash 7a919823e97b04e5e544151c98666d71ace48198,
on macOS, the --fps option seems to have no effect.
at least, low values such as `--fps 2` are rendering way faster than 2 fps.

**Comment by elenzil** [comment]
introduced [here](https://github.com/jshrake/grimoire/commit/ee543ff9e213e9add5e6e42faac5b5abc838c801#diff-639fbc4ef05b315af92b4d836c31b023L358)

**Comment by elenzil** [comment]
fwiw, my main use for this is to reduce battery consumption while developing a shader.

**Comment by jshrake** [comment]
Thanks for this, I initially added this code for the same reason. The code was inadvertently removed while I was hunting down a performance issue on Windows 10 that ended up being related to RGB LED fan controller drivers.
